"""Clair v4 adapter: `clairctl report --out json` against the in-cluster Clair (combo mode)."""

from __future__ import annotations

import asyncio
import ipaddress
import json
import os
import socket
import re
from datetime import datetime
from typing import Any

import httpx

from ..severity import normalize_severity
from .base import Finding, ScanResult, Scanner, extract_cve, first_float, parse_time, run_proc, tail

NAME = "clair"

CLAIRCTL_CONFIG_TEMPLATE = """\
# Generated by nebari-security-posture worker. clairctl only needs this file to exist
# (it reads auth settings from it); the mirror registry ({mirror}) is plain-http
# and is reached by clairctl's http fallback for insecure registries.
http_listen_addr: ":6060"
introspection_addr: ":8089"
log_level: info
indexer:
  connstring: ""
  migrations: false
matcher:
  connstring: ""
  migrations: false
notifier: {{}}
auth: {{}}
"""


def write_clairctl_config(cache_dir: str, mirror_registry: str) -> str:
    path = os.path.join(cache_dir, "clairctl", "config.yaml")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(CLAIRCTL_CONFIG_TEMPLATE.format(mirror=mirror_registry))
    return path


def _first_json_object(text: str) -> Any:
    dec = json.JSONDecoder()
    text = text.lstrip()
    idx = 0
    while idx < len(text):
        try:
            obj, _ = dec.raw_decode(text, idx)
            return obj
        except json.JSONDecodeError:
            nxt = text.find("{", idx + 1)
            if nxt < 0:
                raise
            idx = nxt
    raise json.JSONDecodeError("no JSON object", text, 0)


def _unwrap_report(doc: Any) -> dict[str, Any]:
    if isinstance(doc, list) and doc:
        doc = doc[0]
    if not isinstance(doc, dict):
        return {}
    if "vulnerabilities" in doc or "package_vulnerabilities" in doc:
        return doc
    for key in ("report", "Report", "vulnerability_report"):
        if isinstance(doc.get(key), dict):
            return doc[key]
    return doc


def _cvss_enrichments(report: dict[str, Any]) -> dict[str, float]:
    out: dict[str, float] = {}
    for key, items in (report.get("enrichments") or {}).items():
        if "cvss" not in key.lower():
            continue
        for item in items or []:
            if not isinstance(item, dict):
                continue
            for vid, entries in item.items():
                for e in entries if isinstance(entries, list) else [entries]:
                    if isinstance(e, dict):
                        s = first_float(e.get("baseScore"))
                        if s and s > out.get(vid, 0):
                            out[vid] = s
    return out


def severity_from_cvss(score: float | None) -> str:
    if score is None:
        return "unknown"
    if score >= 9.0:
        return "critical"
    if score >= 7.0:
        return "high"
    if score >= 4.0:
        return "medium"
    if score > 0:
        return "low"
    return "negligible"


def parse_clair_json(doc: Any) -> tuple[list[Finding], dict[str, Any]]:
    """Parse a claircore VulnerabilityReport (as printed by `clairctl report --out json`)."""
    report = _unwrap_report(doc)
    packages = report.get("packages") or {}
    vulns = report.get("vulnerabilities") or {}
    cvss_by_vid = _cvss_enrichments(report)
    findings: list[Finding] = []
    for pkg_id, vids in (report.get("package_vulnerabilities") or {}).items():
        pkg = packages.get(pkg_id) or {}
        for vid in vids or []:
            v = vulns.get(vid)
            if not v:
                continue
            name = v.get("name") or ""
            links = v.get("links") or ""
            cve = extract_cve(name, links)
            vuln_id = cve or (name.split()[0] if name else vid)
            cvss = cvss_by_vid.get(vid)
            sev = normalize_severity(v.get("normalized_severity") or v.get("severity"))
            if sev == "unknown" and cvss:
                sev = severity_from_cvss(cvss)
            url = links.split()[0] if links else None
            desc = (v.get("description") or "").strip()
            vpkg = v.get("package") or {}
            kind = pkg.get("kind") or vpkg.get("kind")
            repo = (v.get("repository") or {}).get("name")
            findings.append(
                Finding(
                    vuln_id=vuln_id,
                    severity=sev,
                    package=pkg.get("name") or vpkg.get("name") or "",
                    installed_version=pkg.get("version"),
                    fixed_version=v.get("fixed_in_version") or None,
                    pkg_type=repo or kind,
                    scanner=NAME,
                    cvss=cvss,
                    title=desc.splitlines()[0][:200] if desc else None,
                    url=url,
                )
            )
    meta: dict[str, Any] = {}
    dists = report.get("distributions") or {}
    if dists:
        d = next(iter(dists.values()))
        meta["os_family"] = d.get("did") or d.get("name")
        meta["os_name"] = d.get("version_id") or d.get("version")
    return findings, meta


def _plain_http_capable(host: str) -> bool:
    """go-containerregistry (used by clairctl) falls back to http only for localhost,
    `*.local` names and private IPs; other insecure hosts are pinned to their IP."""
    h = host.rsplit(":", 1)[0] if host.count(":") == 1 else host
    if h == "localhost" or h.endswith(".local"):
        return True
    try:
        return ipaddress.ip_address(h).is_private
    except ValueError:
        return False


def pin_insecure_host(ref: str) -> str:
    host, sep, rest = ref.partition("/")
    if not sep or _plain_http_capable(host):
        return ref
    name, _, port = host.partition(":")
    try:
        ip = socket.getaddrinfo(name, None, socket.AF_INET)[0][4][0]
    except OSError:
        return ref
    if not ipaddress.ip_address(ip).is_private:
        return ref
    return f"{ip}{':' + port if port else ''}/{rest}"


class ClairScanner(Scanner):
    name = NAME

    def __init__(self, clair_url: str, binary: str = "clairctl", cache_dir: str = "/cache",
                 mirror_registry: str = "", docker_config: str | None = None):
        self.clair_url = clair_url.rstrip("/")
        self.binary = binary
        self.cache_dir = cache_dir
        self.mirror_registry = mirror_registry
        self.docker_config = docker_config
        self._config_path: str | None = None

    def config_path(self) -> str:
        if not self._config_path or not os.path.exists(self._config_path):
            self._config_path = write_clairctl_config(self.cache_dir, self.mirror_registry)
        return self._config_path

    async def version(self) -> str | None:
        res = await run_proc([self.binary, "--version"], 30)
        m = re.search(r"v?(\d+\.\d+\.\d+)", res.stdout + res.stderr)
        return m.group(1) if m else None

    async def update_operations(self) -> dict[str, Any] | None:
        """`{updater: [ops]}` from the matcher's internal update_operation API (None if unreachable)."""
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                r = await client.get(f"{self.clair_url}/matcher/api/v1/internal/update_operation",
                                     params={"latest": "true"})
                r.raise_for_status()
                return r.json() or {}
        except Exception:
            return None

    async def db_updated_at(self) -> datetime | None:
        """Latest updater run, from the matcher's internal update_operation API."""
        data = await self.update_operations()
        if data is None:
            return None
        latest: datetime | None = None
        for ops in (data or {}).values():
            for op in ops or []:
                dt = parse_time(op.get("date"))
                if dt and (latest is None or dt > latest):
                    latest = dt
        return latest

    async def healthy(self) -> tuple[bool, str | None]:
        try:
            async with httpx.AsyncClient(timeout=5) as client:
                r = await client.get(f"{self.clair_url}/indexer/api/v1/index_state")
                return r.status_code == 200, None if r.status_code == 200 else f"index_state {r.status_code}"
        except Exception as e:  # noqa: BLE001
            return False, f"clair unreachable: {e}"

    def argv(self, ref: str) -> list[str]:
        return [self.binary, "-q", "-c", self.config_path(), "report", "--host", self.clair_url + "/",
                "--out", "json", ref]

    async def scan(self, ref: str, *, insecure: bool = False, timeout: float = 600) -> ScanResult:
        env = {}
        if self.docker_config:
            env["DOCKER_CONFIG"] = self.docker_config
        if insecure:
            ref = await asyncio.to_thread(pin_insecure_host, ref)
        res = await run_proc(self.argv(ref), timeout, env)
        if res.timed_out:
            return ScanResult(NAME, "timeout", error=f"timed out after {int(timeout)}s", duration_ms=res.duration_ms)
        if res.returncode != 0 or not res.stdout.strip():
            return ScanResult(NAME, "error", error=tail(res.stderr or res.stdout) or f"exit {res.returncode}",
                              duration_ms=res.duration_ms)
        try:
            doc = _first_json_object(res.stdout)
        except json.JSONDecodeError as e:
            return ScanResult(NAME, "error", error=f"invalid JSON from clairctl: {e}", duration_ms=res.duration_ms,
                              raw=res.stdout)
        findings, meta = parse_clair_json(doc)
        return ScanResult(NAME, "ok", findings=findings, duration_ms=res.duration_ms, raw=res.stdout,
                          os_family=meta.get("os_family"), os_name=meta.get("os_name"))
