"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 19:27:28.144731
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('ref', sa.Text(), nullable=False),
    sa.Column('registry', sa.String(length=255), nullable=False),
    sa.Column('repository', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('digest', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=8), nullable=True),
    sa.Column('counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fixable', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scanners', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('agreement_index', sa.Float(), nullable=True),
    sa.Column('namespaces', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('workloads', sa.Integer(), nullable=False),
    sa.Column('containers', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=False),
    sa.Column('mirrored', sa.Boolean(), nullable=False),
    sa.Column('mirror_ref', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('os_family', sa.String(length=64), nullable=True),
    sa.Column('os_name', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_images_digest'), 'images', ['digest'], unique=False)
    op.create_index(op.f('ix_images_running'), 'images', ['running'], unique=False)
    op.create_table('scanner_status',
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('db_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('scans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('force', sa.Boolean(), nullable=False),
    sa.Column('target_image_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('target_namespaces', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('images_total', sa.Integer(), nullable=False),
    sa.Column('images_done', sa.Integer(), nullable=False),
    sa.Column('images_failed', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('vuln_score', sa.Float(), nullable=True),
    sa.Column('posture_score', sa.Float(), nullable=True),
    sa.Column('per_scanner', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('inventory_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('beat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consensus_findings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('scan_id', sa.BigInteger(), nullable=True),
    sa.Column('vuln_id', sa.String(length=128), nullable=False),
    sa.Column('package', sa.Text(), nullable=False),
    sa.Column('installed_version', sa.Text(), nullable=True),
    sa.Column('fixed_version', sa.Text(), nullable=True),
    sa.Column('pkg_type', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('scanners', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('per_scanner', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('agreement', sa.Float(), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('fixable', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'vuln_id', 'package', name='uq_consensus_image_vuln_pkg')
    )
    op.create_index(op.f('ix_consensus_findings_image_id'), 'consensus_findings', ['image_id'], unique=False)
    op.create_index('ix_consensus_vuln', 'consensus_findings', ['vuln_id'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.BigInteger(), nullable=False),
    sa.Column('namespace', sa.String(length=253), nullable=False),
    sa.Column('pod', sa.String(length=253), nullable=False),
    sa.Column('container', sa.String(length=253), nullable=False),
    sa.Column('container_type', sa.String(length=16), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('image_id_raw', sa.Text(), nullable=True),
    sa.Column('image_fk', sa.BigInteger(), nullable=True),
    sa.Column('workload_kind', sa.String(length=64), nullable=False),
    sa.Column('workload_name', sa.String(length=253), nullable=False),
    sa.Column('pack', sa.String(length=255), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=False),
    sa.Column('pod_phase', sa.String(length=32), nullable=True),
    sa.Column('security', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['image_fk'], ['images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_containers_image_fk'), 'containers', ['image_fk'], unique=False)
    op.create_index('ix_containers_scan_ns', 'containers', ['scan_id', 'namespace'], unique=False)
    op.create_table('image_scans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('scanner', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('db_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('scanned_ref', sa.Text(), nullable=True),
    sa.Column('raw_gz', sa.LargeBinary(), nullable=True),
    sa.Column('raw_size', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_scans_image_id'), 'image_scans', ['image_id'], unique=False)
    op.create_index(op.f('ix_image_scans_scan_id'), 'image_scans', ['scan_id'], unique=False)
    op.create_table('posture_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.BigInteger(), nullable=False),
    sa.Column('check_id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=253), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=253), nullable=False),
    sa.Column('pod', sa.String(length=253), nullable=True),
    sa.Column('container', sa.String(length=253), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('system_namespace', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posture_scan_check', 'posture_results', ['scan_id', 'check_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('scope_kind', sa.String(length=16), nullable=False),
    sa.Column('scope_name', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_scan_id'), 'reports', ['scan_id'], unique=False)
    op.create_index('ix_reports_type_created', 'reports', ['type', 'created_at'], unique=False)
    op.create_table('scan_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_scan_level', 'scan_snapshots', ['scan_id', 'level'], unique=False)
    op.create_table('workloads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.BigInteger(), nullable=False),
    sa.Column('namespace', sa.String(length=253), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=253), nullable=False),
    sa.Column('pack', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('vuln_score', sa.Float(), nullable=True),
    sa.Column('posture_score', sa.Float(), nullable=True),
    sa.Column('containers', sa.Integer(), nullable=False),
    sa.Column('running_containers', sa.Integer(), nullable=False),
    sa.Column('image_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('posture_passed', sa.Integer(), nullable=False),
    sa.Column('posture_failed', sa.Integer(), nullable=False),
    sa.Column('counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('system_namespace', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workloads_scan_ns', 'workloads', ['scan_id', 'namespace'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('image_scan_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('scanner', sa.String(length=16), nullable=False),
    sa.Column('vuln_id', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('package', sa.Text(), nullable=False),
    sa.Column('installed_version', sa.Text(), nullable=True),
    sa.Column('fixed_version', sa.Text(), nullable=True),
    sa.Column('pkg_type', sa.String(length=64), nullable=True),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_scan_id'], ['image_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_image_id'), 'findings', ['image_id'], unique=False)
    op.create_index(op.f('ix_findings_image_scan_id'), 'findings', ['image_scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_image_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_image_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_workloads_scan_ns', table_name='workloads')
    op.drop_table('workloads')
    op.drop_index('ix_snapshots_scan_level', table_name='scan_snapshots')
    op.drop_table('scan_snapshots')
    op.drop_index('ix_reports_type_created', table_name='reports')
    op.drop_index(op.f('ix_reports_scan_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_posture_scan_check', table_name='posture_results')
    op.drop_table('posture_results')
    op.drop_index(op.f('ix_image_scans_scan_id'), table_name='image_scans')
    op.drop_index(op.f('ix_image_scans_image_id'), table_name='image_scans')
    op.drop_table('image_scans')
    op.drop_index('ix_containers_scan_ns', table_name='containers')
    op.drop_index(op.f('ix_containers_image_fk'), table_name='containers')
    op.drop_table('containers')
    op.drop_index('ix_consensus_vuln', table_name='consensus_findings')
    op.drop_index(op.f('ix_consensus_findings_image_id'), table_name='consensus_findings')
    op.drop_table('consensus_findings')
    op.drop_table('worker_heartbeat')
    op.drop_table('settings')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('scanner_status')
    op.drop_index(op.f('ix_images_running'), table_name='images')
    op.drop_index(op.f('ix_images_digest'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
