"""Hardware/Software inventory (eMASS asset-list style): xlsx (Images, Workloads,
Namespaces, Info sheets) or csv (Images only)."""

from __future__ import annotations

import csv
import io
from typing import Any

from ._common import SCANNERS, TOOL_NAME, View, filename, iso, normalize
from .registry import GeneratedReport

XLSX_CT = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
CSV_CT = "text/csv; charset=utf-8"

IMAGE_COLUMNS = [
    "Asset Type", "Image Reference", "Registry", "Repository", "Tag / Version", "Digest", "Base OS",
    "Namespaces", "Workloads", "Pack / NebariApp", "Containers", "Running Containers", "Running",
    "Score", "Grade", "Critical", "High", "Medium", "Low", "Negligible", "Unknown", "Fixable Critical",
    "Fixable High", "Trivy", "Grype", "Clair", "Scanner Coverage", "Agreement Index", "Last Scanned (UTC)",
    "Mirrored", "Warnings",
]
WORKLOAD_COLUMNS = ["Namespace", "Kind", "Name", "Pack / NebariApp", "Containers", "Running", "Score", "Grade",
                    "Images", "Posture Passed", "Posture Failed", "System Namespace"]
NAMESPACE_COLUMNS = ["Namespace", "Pack / NebariApp", "Managed", "Workloads", "Images", "Score", "Grade",
                     "System Namespace"]


def _image_rows(v: View) -> list[list[Any]]:
    rows = []
    for i in sorted(v.images, key=lambda i: i.ref):
        st = i.scanner_status or {}
        ok = [s for s in SCANNERS if st.get(s) == "ok"]
        rows.append([
            "Software (container image)", i.ref, i.registry, i.repository, i.tag, i.digest, i.os,
            ", ".join(i.namespaces), "\n".join(i.workloads), ", ".join(i.packs), i.containers,
            i.running_containers, "Yes" if i.running else "No",
            i.score, i.grade, *[int((i.counts or {}).get(s, 0)) for s in
                                ("critical", "high", "medium", "low", "negligible", "unknown")],
            int((i.fixable or {}).get("critical", 0)), int((i.fixable or {}).get("high", 0)),
            *[st.get(s, "") for s in SCANNERS], f"{len(ok)}/{len(SCANNERS)}",
            round(i.agreement_index, 3) if i.agreement_index is not None else None,
            iso(i.last_scanned_at), "Yes" if i.mirrored else "No", "; ".join(i.warnings),
        ])
    return rows


def _workload_rows(v: View) -> list[list[Any]]:
    refs = {i.id: i.ref for i in v.images}
    return [[w.namespace, w.kind, w.name, w.pack or "", w.containers, "Yes" if w.running else "No", w.score,
             w.grade, "\n".join(refs.get(x, str(x)) for x in w.image_ids), (w.posture or {}).get("passed", 0),
             (w.posture or {}).get("failed", 0), "Yes" if w.system_namespace else "No"]
            for w in sorted(v.workloads, key=lambda w: w.key)]


def _namespace_rows(v: View) -> list[list[Any]]:
    return [[n.name, n.pack or "", "Yes" if n.managed else "No", n.workloads, n.images, n.score, n.grade,
             "Yes" if n.system_namespace else "No"] for n in v.namespaces]


def _xlsx(v: View) -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    wb.remove(wb.active)
    fill = PatternFill("solid", fgColor="E7C4FF")
    for title, cols, rows in (("Images", IMAGE_COLUMNS, _image_rows(v)),
                              ("Workloads", WORKLOAD_COLUMNS, _workload_rows(v)),
                              ("Namespaces", NAMESPACE_COLUMNS, _namespace_rows(v))):
        ws = wb.create_sheet(title)
        ws.append(cols)
        for c in ws[1]:
            c.font, c.fill = Font(bold=True), fill
        for r in rows:
            ws.append(r)
        for idx, col in enumerate(cols, start=1):
            width = 48 if col in ("Image Reference", "Workloads", "Images", "Digest") else max(10, len(col) + 2)
            ws.column_dimensions[get_column_letter(idx)].width = width
        for row in ws.iter_rows(min_row=2):
            for c in row:
                c.alignment = Alignment(vertical="top", wrap_text=True)
        ws.freeze_panes = "C2" if title == "Images" else "B2"
        ws.auto_filter.ref = f"A1:{get_column_letter(len(cols))}{max(ws.max_row, 1)}"
    info = wb.create_sheet("Info")
    for k, val in [("Report", "Hardware/Software inventory"), ("System", v.system.name),
                   ("Organization", v.system.organization), ("Scope", v.scope_label), ("Scan ID", v.scan.id),
                   ("Scan finished (UTC)", iso(v.scan.finished_at)), ("Generated (UTC)", iso(v.generated_at)),
                   ("Generated by", TOOL_NAME), ("Images", len(v.images)), ("Workloads", len(v.workloads)),
                   ("Namespaces", len(v.namespaces))]:
        info.append([k, val])
        info.cell(row=info.max_row, column=1).font = Font(bold=True)
    info.column_dimensions["A"].width = 24
    info.column_dimensions["B"].width = 60
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def _csv(v: View) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\r\n")
    w.writerow(IMAGE_COLUMNS)
    for r in _image_rows(v):
        w.writerow(["; ".join(x.split("\n")) if isinstance(x, str) else ("" if x is None else x) for x in r])
    return buf.getvalue().encode("utf-8-sig")


def generate(fmt: str, snapshot: Any, options: dict[str, Any]) -> GeneratedReport:
    v = normalize(snapshot, options)
    if fmt == "xlsx":
        return GeneratedReport(_xlsx(v), filename(v, "inventory", "xlsx"), XLSX_CT)
    return GeneratedReport(_csv(v), filename(v, "inventory", "csv"), CSV_CT)
